language: node_js
node_js: node
script:
- npm run lint
- polymer test --skip-plugin local
addons:
  jwt:
    secure: P650Af+HQc1c/qBYaJgV7OT6U6ojCFgZ69qAk0bOWj7vnPw+uZj1wYdRXyYhgLpvFJYaJrs8EHQfhXB79ryP/K11qtK2A/O29Q4yiUDGRrsinsNOz/Hw/q9KdqAvoe4rs3iuaavNQ5h7+45ckRl3ooiLlvxi+qYYa+i59A7jkoy+0cNEucubIS4KwkECH3CJ5+dFQHnNLGid21y/W1YfNGAZc4FStC7YcHjiFkAsf6v3oaPZKEwGTfVz0VzZa/dfMuWlJJxjwRw4TxJWNZvZeaaUKo/ShdKSf0xbuaKFbDTJBtMiujvZIYo+VQxP/sqAVZqM1hUyXuipOa9ux4HRfGZkz64+FHhsgV5lS2ixmbXptynjh0sj3Bxq0SaTt+c4QwE+Q1sVeGJRTVyWDuI6ibvPe2daMZ/RKHrVhgosUJF4UL3Sj+Qag/oxB3RF3ub+6z6k+vZOtVseh+djJX7OQHxPs+7ccWpAI5zX8ntg4V8yfr9BiljZ2dg4/uE7OX0CAkNjM9/1cN0Zup+dYIhLO1usfiB6BNLR3L5SR6XWGd4/bFuIUlU0NLKIfouUgbztyamOo+20qCZlLk4ZgHgWzx72/9P3bKkdVQE3+mxy+gMl6b3/aopsdmdUOuLmN+s/HUpOPj+MDPH2+phczeYTjt0r/KT5nXjztyxdk/hwHIU=
env:
  global:
    SAUCE_USERNAME: Desire2Learn
