language: node_js
node_js: stable
script:
- npm run test
- wct --skip-plugin local
addons:
  jwt:
    secure:"1axrKVK+1IswADS3HihwQQoWajcg1b5T0/pIBjhEKCTwxbfoRmxQyTg45FMn+6Dsonurzm6CETuKXIJNsbqCz91EbAx0w4YXN58f07ywYs46KhM5YL96TbxI9HfoFuM4lYXQA8+4uh/Xc4b4KChP9svQOa6Q6GE2h4nC+zyMy6KU5PkxKj1YkvPR+GqU1X0qmLztrAnNIomNKyDQXHP58mnBKDmtA48VaIfQhuG7oiUGWlgWQFHCUz2ycIxZ5dN/jnmUqEjO5fQgLvQ8t4UiRELGZuPAbvaIEWCEeCKb2NsyO6+H3qQyboqhPb08eKxk6Ic++W+105vNbOEdJi4eBxDMyl7/Nogt1Vfue+ZmezsVSm0iMATWeE128Sz980Xfk+/VzccVITm6g9mrA6bz1tB5bRwnLRv6v0E0CgAwy+f3WGbkY2JOFiHf4pZzzfz8Y3yCyWzHHniSsVcXP25pqOSYgfaYzxRyKe89ziv5xVa7sGhDp1FUphKdnLDT1CjspCJcqYlijWahUhNqo3jFEojgZIh1xPkNRev3ECZSrf3M8Ix+b13xe9Ev8D/4gTH3OBooCejJ8d/pTSqGe0uuFjAry3zLj7XaP+C6VD7TL+XgNaB0ZBrBI+RIlGEog4+5ZKvC9Y1U6xlja7QbQWLh/l9HrjpdmAKa0GLXTjRKUQw="
env:
  global:
    SAUCE_USERNAME: Rodolfo-Landa
