language: node_js
node_js: stable
script:
- npm run test
- wct --skip-plugin local
addons:
  jwt:
    secure: 2g8p7FFbDV0fHInmT+UprIsEGb3IUSbk2BbMd7ClX9YoCHGKCzUBD5NGnua96AhHFmRLyZraEzEfhczak2MsHRPzSZ6C/6JschdMPOONfNVucmSmEbUhnUcpyheGwz3rHQkaCJS+BVD0pKTHRyyhCblgUaCX7XhjNxXGsYBTGnGYT07HWVKKYwsGfuIblOidku1ue8wgh/NlV+ByPrbyvRfnuoGRbYvInAkQCVUxIbrJTrlwQb11YAA5Ipf1SnEjRGbQ6UbnnRPsIXc6zZh5PPCnItpDhOHPsUQDB0kGJCVbXcYrtxQ1KPtd3eDNst2n7KuUkFue3xt9CeYvmnHfXRGMJungr+e9rdR0eeVB1txHWGgpxDJSsxkffxgUcAcvCBRRrq1+rphTYbT9AsiPPV2C0ds/fQTwomyAYJ/YzBPyzWobxernnD0XtvO/jGQopCQoKCZXBhD4KOvAmvc0OCkRovgpqsf1hrZYIAxNMGdjaNRp0IgXvLepyjPzD2K1RKSUT8qp96y8cl2Gscwe/peXsTAhnZY92si2nxWtIotqSMR0gWofRRF4//WY+l7fEVUmXwC2s3vq1eZ1crKDvjicwPkV6ylxAR0GvEYy3BeOw9wuhzuyUMzY/iVTa1o7qfsyiw9WydmbF+S34nJz+WXB1irComgXkfZylytPpkQ=
env:
- SAUCE_USERNAME=RodolfoLanda
