language: node_js
node_js: stable
script:
- npm run test
- wct --skip-plugin local
addons:
  jwt:
    secure: buntWUnMstMYDaR/rb2z7eKdIcE1yuSCza6XcyrcVc4g+Uwcl04ODNMMjbHJkHh8gbdS7vyrd7fimrm2DawCl8DV8Nz0Lsh3aUJS87Qx4Tw7bYPsQ5ClFfuvoIANoL0x2+GrnXWDKWou3Wp3ORuTHH3u8Kz3dUfTgbIwljsXDaTv9AIFMUYF63lDlnsE6zvIAstg15OZoCWx6rGUOILVKtV4vTd87HrrmT6SokFfg6WDUjPqHVxQhjvpE+/XNpity5MWtPFELz7mEDHKlqvM3sc73BC+gKavVfgUFtySExsXQxS8ZZScjPVj6aVj0BJPhWmpIu8JB6RSQvXK3C8T3IEAa+0Kr8+7TGKsPGPlBUqXEd17EltLk2XDSi5H6rjUg0Ptl+rDZ43C6r7BEOIUZgZcM6iz9jHWMlK6OnBMDAEgbDiDPNOAI+UVxutIw88NZXSVSCj7cKVMemSFt4OKWrSmo3T0XsUYB7YV0b+QAMgw8V05FRFqbff+qQSDkJaVjso2ArHueKMrAPfTZoScbiEqL4OsRRMB0Y7D0xDrJp/zFf2HjbJphaC7EhcJbCXuLKo9gD4XycVRwyb+PbC+mi7deQs6X7WWUTG0GSC51PfPYUXnVprchZfy4xih87LbK+118TafSvKqryZkGpzjtX7D1pTwUljyDgZCG7SJrfw=
env:
  - SAUCE_USERNAME=Rodolfo-Landa
