language: node_js
node_js: stable
script:
- npm run test
- wct --skip-plugin local
addons:
  sauce_connect: true
  jwt:
    secure:DiJUnXvv30IeSt1JuTcsZqgDUGJEFEIVQF0CwRORCtC7atcGdc0d9dhtHKOdb9mp6y1WmyQ2QmczlhaDede7nxIqFYkgKe56CeXtv8hWETFwsHVD1Sse3cZ9jn7lFWdn7bOfLwCIOiAAl6ipEJZT+XDFTPGxYeRNNYlw5mB2/b7xvUSPbS5tIN6yOm5clHDaAju9007GPrC6aaJ6+wcNJWDZDRoKsCdnZ2L16VzjkyPyV8y6eTCdho6bjaBiHDRrGC+RUS50i4eTvi8HkPZCwuUe3iG8mrXnkjGh4r1JbS5BfEmp0H6F5R+g5oT4HJfy+SROhQwPPebUN/W13e6TZDCbRvkNU4yCaQ0CN1ySdga+mY1P6wo4TtJpp+xGV5h4H3sEWCf6OUM0MrpTGzjEH5+nbiPrajNXFXFwg7DeWH9E/VkFQFkLOHxOd9JLxuSs68/GR08INM0WP6CVUxC5lnVYJypDOFe5lhLR20hZHyqBVgMYQkiR5yFYVo80D3XTH2SOR6iSeZwX2apzxWJrdmMTp8jkok7ixHHCdJEjtHgFSsLF+axsLfBYB0V598Tm5s/aHWld+8DIYLSzNZWU+yQnFlXQwl3wf/m1uyjahkYGpoIdGJHwVmLTVg0khflLszC/6YQXkR+GQz8vjW5iRxM9iBhSSoD8CVjoajQSm2o=
env:
  global:
    SAUCE_USERNAME: Rodolfo-Landa
   
